name: Build Pipeline
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch'
        required: true
        default: 'master'
      folder:
        description: 'Select the folder which contain your services'
        required: true
        type: choice
        options:
          - core-services
          - business-services
      serviceName:
        description: 'Provide the service name you want to build'
        required: true
      dbMigration:
        description: Enable if you require db migration to this service
        required: true
        type: boolean
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow dispatch is triggered
        if: github.event_name == 'workflow_dispatch'
        run: echo "Workflow dispatched to branch ${{ github.event.inputs.branch }}"

      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: 
            work-dir: "core-services/audit-service"
          file: /build/maven/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.serviceName }}:${{ github.event.inputs.branch }}

      - name: Archive core-services folder
        run: tar -czf core-services.tar.gz core-services/

      - name: Upload core-services folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: core-services-artifact
          path: core-services.tar.gz

      - name: Change working directory
        run: pwd
        working-directory: ${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}