name: Build Pipeline
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch'
        required: true
        default: 'master'
      folder:
        description: 'Select the folder which contain your services'
        required: true
        type: choice
        options:
          - core-services
          - business-services
      serviceName:
        description: 'Provide the service name you want to build'
        required: true
      dbMigration:
        description: Enable if you require db migration to this service
        required: true
        type: boolean
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow dispatch is triggered
        if: github.event_name == 'workflow_dispatch'
        run: echo "Workflow dispatched to branch ${{ github.event.inputs.branch }}"

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Archive business-services folder
        run: tar -czf business-services.tar.gz business-services/

      - name: Upload business-services folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: business-services-artifact
          path: business-services.tar.gz
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: build/maven/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.inputs.serviceName }}:${{ github.event.inputs.branch }}
          build-args: WORK_DIR=${{ github.event.inputs.folder }}/${{ github.event.inputs.serviceName }}

