name: Build Pipeline
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch'
        required: true
        default: ''
jobs:
  list-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Displaying the branch name
        run: echo ${{ github.ref.name }}
