name: Build Pipeline
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch'
        required: true
jobs:
  list-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Displaying the branch name
        run: echo ${{ github.ref_name }}