name: Build Pipeline
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch'
        required: true
        default: main
jobs:
  list-branches:
    runs-on: ubuntu-latest
    steps:
      - name: List Branches
        id: list_branches
        uses: softprops/action-repo-branches@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Displaying the branch name
        run: echo "${{ github.event.inputs.branch }}"
